spring:
  datasource:
    url: "${custom.secret.db.local.url}"
    username: "${custom.secret.db.local.username}"
    password: "${custom.secret.db.local.password}"
    driver-class-name: com.mysql.cj.jdbc.Driver