server:
  port: 8080
spring:
  output:
    ansi:
      enabled: ALWAYS
  profiles:
    active: local
    include: secret
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
  docker:
    compose:
      enabled: false

webrtc:
  ice-servers:
    - urls: stun:stun.l.google.com:19302

custom:
  site:
    frontUrl: "http://${custom.site.cookieDomain}:5173"
    backUrl: "http://${custom.site.cookieDomain}:${server.port}"
